config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :users
  resources :phones
  resources :restaurant_highlights
  resources :highlights
  resources :restaurant_cuisins
  resources :restaurants
  resources :cuisins
  resources :locations
  resources :cities

end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/cuisin.rb
class Cuisin < ActiveRecord::Base
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/phone.rb
class Phone < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/restaurant_cuisin.rb
class RestaurantCuisin < ActiveRecord::Base
end

app/models/restaurant_highlight.rb
class RestaurantHighlight < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/restaurant_highlights_controller.rb
class RestaurantHighlightsController < ApplicationController
  before_action :set_restaurant_highlight, only: [:show, :edit, :update, :destroy]

  # GET /restaurant_highlights
  # GET /restaurant_highlights.json
  def index
    @restaurant_highlights = RestaurantHighlight.all
  end

  # GET /restaurant_highlights/1
  # GET /restaurant_highlights/1.json
  def show
  end

  # GET /restaurant_highlights/new
  def new
    @restaurant_highlight = RestaurantHighlight.new
  end

  # GET /restaurant_highlights/1/edit
  def edit
  end

  # POST /restaurant_highlights
  # POST /restaurant_highlights.json
  def create
    @restaurant_highlight = RestaurantHighlight.new(restaurant_highlight_params)

    respond_to do |format|
      if @restaurant_highlight.save
        format.html { redirect_to @restaurant_highlight, notice: 'Restaurant highlight was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant_highlight }
      else
        format.html { render :new }
        format.json { render json: @restaurant_highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurant_highlights/1
  # PATCH/PUT /restaurant_highlights/1.json
  def update
    respond_to do |format|
      if @restaurant_highlight.update(restaurant_highlight_params)
        format.html { redirect_to @restaurant_highlight, notice: 'Restaurant highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant_highlight }
      else
        format.html { render :edit }
        format.json { render json: @restaurant_highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_highlights/1
  # DELETE /restaurant_highlights/1.json
  def destroy
    @restaurant_highlight.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_highlights_url, notice: 'Restaurant highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_highlight
      @restaurant_highlight = RestaurantHighlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_highlight_params
      params.require(:restaurant_highlight).permit(:restaurant_id, :highlight_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :mobile, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/cuisins_helper.rb
module CuisinsHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/restaurant_highlights_helper.rb
module RestaurantHighlightsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/restaurant_highlights/_form.html.erb
<%= form_for(@restaurant_highlight) do |f| %>
  <% if @restaurant_highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant_highlight.errors.count, "error") %> prohibited this restaurant_highlight from being saved:</h2>

      <ul>
      <% @restaurant_highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.text_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :highlight_id %><br>
    <%= f.text_field :highlight_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurant_highlights/edit.html.erb
<h1>Editing Restaurant Highlight</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_highlight %> |
<%= link_to 'Back', restaurant_highlights_path %>

app/views/restaurant_highlights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurant Highlights</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Highlight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_highlights.each do |restaurant_highlight| %>
      <tr>
        <td><%= restaurant_highlight.restaurant_id %></td>
        <td><%= restaurant_highlight.highlight_id %></td>
        <td><%= link_to 'Show', restaurant_highlight %></td>
        <td><%= link_to 'Edit', edit_restaurant_highlight_path(restaurant_highlight) %></td>
        <td><%= link_to 'Destroy', restaurant_highlight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant highlight', new_restaurant_highlight_path %>

app/views/restaurant_highlights/new.html.erb
<h1>New Restaurant Highlight</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_highlights_path %>

app/views/restaurant_highlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @restaurant_highlight.restaurant_id %>
</p>

<p>
  <strong>Highlight:</strong>
  <%= @restaurant_highlight.highlight_id %>
</p>

<%= link_to 'Edit', edit_restaurant_highlight_path(@restaurant_highlight) %> |
<%= link_to 'Back', restaurant_highlights_path %>