config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :users
  resources :phones
  resources :restaurant_highlights
  resources :highlights
  resources :restaurant_cuisins
  resources :restaurants
  resources :cuisins
  resources :locations
  resources :cities

end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]

  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to @highlight, notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else
        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to @highlight, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:name)
    end
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/views/highlights/_form.html.erb
<%= form_for(@highlight) do |f| %>
  <% if @highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% @highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing Highlight</h1>

<%= render 'form' %>

<%= link_to 'Show', @highlight %> |
<%= link_to 'Back', highlights_path %>

app/views/highlights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Highlights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%= highlight.name %></td>
        <td><%= link_to 'Show', highlight %></td>
        <td><%= link_to 'Edit', edit_highlight_path(highlight) %></td>
        <td><%= link_to 'Destroy', highlight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highlight', new_highlight_path %>

app/views/highlights/new.html.erb
<h1>New Highlight</h1>

<%= render 'form' %>

<%= link_to 'Back', highlights_path %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @highlight.name %>
</p>

<%= link_to 'Edit', edit_highlight_path(@highlight) %> |
<%= link_to 'Back', highlights_path %>